### ISSUE TITLE
Installation issue b/c of d3Network package dependency?

### ISSUE THREAD

**Issue by mi302** [neuropsychology/psycho.R#105]
While trying to install psycho package, R (3.5 Linux) returns non-zero exit status. I suspect this is because of R's inability to install the 'd3Network' package. I tried to install 'd3Network' manually but it also returns a non-zero exist status. 

I was wondering if the issues is because of 

> "**Development has moved to networkD3. d3Network is no longer supported**"

, as described on http://christophergandrud.github.io/d3Network/. I tried installing 'networkD3' too; the package installs fine, but R still cannot install 'psycho'. 

I would appreciate any help to get it to work?

**Comment by DominiqueMakowski** [comment]
@mi302 Hum, I am afraid psycho doesn't rely directly on network3D, and I am not sure which of its deps is depending on it... I am not sure how to address that. 

However, know that most of psycho's functions are currently being reimplemented within the [easystats](https://github.com/easystats), for instance in [report](https://github.com/easystats/report). Let me know what "aspects" of psycho were you seeking, and I can tell you if it's already or planned to be implemented in easytats.

**Comment by mi302** [comment]
Wow! That was an amazingly quick response! 

I am actually trying to use the "get_contrasts()" function to extract from a lmer object the statistics related to means and pairwise differences.  (I wrote some functions that call this function, and now that I can't get 'psycho' to work, my functions are non-functional too). 

Is easystats an R package, BTW? Please bear with my ignorance. I appreciate your help!

**Comment by DominiqueMakowski** [comment]
[easysats](https://github.com/easystats/) in a collection of packages that will eventually replace most of psycho's functions (it is a work in progress). 

Your case is unfortunate: the get_means and get_contrasts of psycho's are meant to be reimplemented in the [estimate](https://github.com/easystats/estimate) (`estimate_contrasts` and `estimate_means`). However, the package currently supports only rstanarm (bayesian) models 😕 

Thus, I would recommend checking the [emmeans](https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html) package, on which get_contrasts was based (see its [source code](https://github.com/neuropsychology/psycho.R/blob/c3a03b406f109c1f14f50df0b82213eb5f3ae272/R/get_contrasts.R#L198)).

Hope it helps

**Comment by mi302** [comment]
Great! I will use the emmeans package, then. Thank you so much for your super quick response and support.
