### ISSUE TITLE
How to deal with the situation when false alarm rate = 0?

### ISSUE THREAD

**Issue by Youguang** [neuropsychology/psycho.R#111]
dprime will be `Inf` when  `HR = 1` and `FA =0`, how to deal with this situation?

**Comment by DominiqueMakowski** [comment]
Hi @Youguang, It is an expected feature of dprime. One way to deal is to use non-parametric indices (e.g., aprime). Another way (which I personally am not fond of, although I know people are using it) is to adjust the numbers to not have FAs of 0 and HRs of 1 by tweaking the data. 

> E.g.: “The identification judgments were used to estimate perceptual distances by calculating the z transform of the mean identification percentage for each token and then taking the absolute value of the difference for each pair of tokens. The z transform reaches infinity when percentages equal 0 or 100, so tokens with 0% identifications were assigned values of 1% and tokens with 100% identifications were assigned values of 99% (Macmillan and Creelman, 1991).” [**here**](http://phonetics.linguistics.ucla.edu/facilities/statistics/dprime.htm)

No other alternatives come to my mind, maybe people have come up with other ideas on the internet? Let us know if you find anything interesting ☺️

**Comment by Youguang** [comment]
Thanks for your reply @DominiqueMakowski. 

[Here](https://stats.stackexchange.com/a/134802/237509) are some references.
And [dprime.R](https://github.com/neuropsychology/psycho.R/blob/611e984742890e698c4e94b6965d917432e98348/R/dprime.R#L77-L79) provided one method, [the third approach](https://stats.stackexchange.com/a/134802/237509), to adjust dprime.
