### ISSUE TITLE
Error on "How to do Repeated Measures ANOVAs in R" tutorial's code

### ISSUE THREAD

**Issue by mtcruz** [neuropsychology/psycho.R#112]
I do not know if issues related to the "The Psycho Blog" should be posted here, but I found no other place to report this issue. I apologize in advance if this is not the proper place.

On the "[How to do Repeated Measures ANOVAs in R](https://neuropsychology.github.io/psycho.R/2018/05/01/repeated_measure_anovas.html)",  written by @DominiqueMakowski,  some code the examples put there do not work. Specifically there seems to be an misunderstanding with what  the `get_contrasts` function does.
The tutorial instructs one to:

> We have to provide the model (here called fit) and the factors we want to contrast
> ```
>results <- get_contrasts(fit, "Emotion_Condition")
> print(results$contrasts)
>```

However this returns `NULL`.
It seems that what was really intended is `print(contrasts)`

On another part of the text it says 

> The best way to do it is to estimate means based on the fitted model (marginal means). **Those were automatically computed when running the get_contrasts function**. We just have to extract them.

However I could not find the estimate means inside of `get_contrast` output. I think `get_means(fit)` would be the way to go here. This error makes plotting the data impossible if one is following the tutorial.

EDIT: The second part of the tutorial that addas participant sex as a factor uses the correct function to get the estimated means.
```r
estimated_means <- get_means(fit, "Emotion_Condition * Participant_Sex")
estimated_means
```
Although I am not sure if `"Emotion_Condition * Participant_Sex"` is needed.

**Comment by DominiqueMakowski** [comment]
@mtcruz Apologies, somehow I missed this issue. For future reference, the new psycho version has been reorganized and some of its functions were improved and moved to other packages:

- https://github.com/neuropsychology/psycho.R/issues/115
- https://github.com/easystats/easystats/issues/58#issuecomment-583349793
