### ISSUE TITLE
The 'correlation' function apparently no longer exists

### ISSUE THREAD

**Issue by LizHareDogs** [neuropsychology/psycho.R#118]
Hi, 

I've been reading that some functions have been removed from the psycho package, after finding out that the correlation function I read about is no longer available.

The functionw as used to prepare correlation tables that had *s indicating significance levels of correlations.

Has this function gone to another package?

Thanks,
Liz

**Comment by DominiqueMakowski** [comment]
Hi, you can find all of these functions and more in this package:

https://github.com/easystats/correlation

**Comment by LizHareDogs** [comment]
Thank you very much!


Liz Hare, PhD
Dog Genetics LLC
***@***.***
http://www.doggenetics.com
