### ISSUE TITLE
bayes_cor.test

### ISSUE THREAD

**Issue by juliapottkaemper** [neuropsychology/psycho.R#119]
Hi all,

I wanted to perform a bayesian correlation analysis on my data. However, when I install the package 'psycho', it says that the function bayes_cor.test does not exist:

---> could not find function "bayes_cor.test"

I found the explanation of this function on the following webiste:

https://www.r-bloggers.com/2018/06/easy-apa-formatted-bayesian-correlation/

Can you help me with this? And if this function does not exist anymore, point me towards another possible solution? Thanks in advance!

Best, Julia

**Comment by DominiqueMakowski** [comment]
Hi @juliapottkaemper, this functionality has been moved to the [correlation package](https://github.com/easystats/correlation#bayesian-correlations) :)
