### ISSUE TITLE
Correlation: wrong direction intepretation (positive - negative)

### ISSUE THREAD

**Issue by mcdussault** [neuropsychology/psycho.R#55]
Hello Dominique!

Thanks for a cool package, the correlation functions are really good for my work. My question is regarding the r values and the printed output. I'm not sure if I'm missing something completely, but in your blog example, the r values in the table are reported as positive, but in the printed pairwise correlations the text output states it is a negative correlation.

For example, in the table Concealing and Age have a reported as -0.05 but in the printed text it is "   - Age / Concealing:   Results of the Pearson correlation showed a non significant and weak positive association between Age and Concealing (r(1249) = -0.050, p > .1)." And the opposite is true for Life Satisfaction and adjusting with r of 0.36 and the text stating "   - Life_Satisfaction / Adjusting:   Results of the Pearson correlation showed a significant and moderate negative association between Life_Satisfaction and Adjusting (r(1249) = 0.36, p < .001***)."

I'm not sure if I'm interpreting things correctly or if I have indeed been interpreting the correlations incorrectly?

Thank you for your help!

Marie

**Comment by DominiqueMakowski** [comment]
Hi @mcdussault, this looks like a bug indeed, thanks for reporting it, I'll look into it :)

**Comment by mcdussault** [comment]
Thank you!

**Comment by DominiqueMakowski** [comment]
@mcdussault I think it has been solved, could you update to the last github version : 
```r
install.packages("devtools")
library("devtools")
install_github("neuropsychology/psycho.R")
library("psycho")
``` 
and validate that the table and the printed output are corectly coherent? Thanks !

**Comment by mcdussault** [comment]
It appears to be working as it should, thank you @DominiqueMakowski !
