### ISSUE TITLE
issue using the package

### ISSUE THREAD

**Issue by anoumouteko** [neuropsychology/psycho.R#56]
Hello,
I came across your package and found it very useful.
But I came across an issue.
I can't use the package.
I downloaded from Git manually and past it in my work folder then unzip it as this:
install.packages('psycho.R-master.zip', lib='//spodwh02/Sas_dwh_p_datamining/90. Datamining Work/Team/Rlibrary',repos = NULL)
Then start as in you example to check wether I get the same results as you.
but when calling the package I have this
Error in library("psycho.R") : there is no package called ‘psycho.R’.
Error in library("psycho") : there is no package called ‘psycho’
This is the first time I get this.
As I can't use devtools::install_github("neuropsychology/psycho.R")  # Install the newest version
 because of security reason .
I usually download things manually when i need the lastest version and it works;
I got the same error when installing packages from traditional way and  repos.
Do you have an idea?
any help?
Thanks

**Comment by DominiqueMakowski** [comment]
@anoumouteko Obviously something went wrong in the package installation, as it is undected by R (no package called psycho). You say that it workss with other packages but not with this one? Does it say something (a warning) after the install.packages() command?

Is it only the install_github that you can't use? Can you download and install the CRAN version?

**Comment by anoumouteko** [comment]
Hello Dominique, same error when installed from CRAN version /
Error in library("psycho.R") : there is no package called ‘psycho.R’.
Error in library("psycho") : there is no package called ‘psycho’

**Comment by DominiqueMakowski** [comment]
@anoumouteko and all other packages work?

**Comment by anoumouteko** [comment]
all the packages work

**Comment by DominiqueMakowski** [comment]
Have you tried downloading the source files from CRAN (https://cran.r-project.org/src/contrib/psycho_0.2.3.tar.gz) and installing it as you did with the zip file?

**Comment by anoumouteko** [comment]
I did it also and same error.
I took it manually , saved it on my work folder then unzip it by this :install.packages('psycho.R-master.zip', lib='//spodwh02/Sas_dwh_p_datamining/90. Datamining Work/Team/Rlibrary',repos = NULL) .
same error

**Comment by DominiqueMakowski** [comment]
I suppose you should change the name and put "psycho_0.2.3.tar.gz" instead of "psycho.R-master.zip"

**Comment by DominiqueMakowski** [comment]
@anoumouteko

**Comment by jenrichmond** [comment]
I have this issue too. The package looks great and I particularly like how you can display model interpretation (nice idea) but I can't make it install properly. Screenshot attached. 

<img width="1280" alt="screenshot 2018-06-14 21 40 54" src="https://user-images.githubusercontent.com/40267093/41410361-9429db4a-701c-11e8-9436-0ba287e99d9e.png">

**Comment by DominiqueMakowski** [comment]
@jenrichmond Thanks,

It seems that the installation fails after trying to load a function from the `stringr` package. Could you try manually install/update stringr using `install.packages("stringr")`? Then trying to install psycho again. Please repaste the error code (or a screenshot) if it fails again thanks!

**Comment by jenrichmond** [comment]
Amazing that works perfectly thanks so much!!

**Comment by kortekss** [comment]
Hi,

I'm having problem about finding the analyse function. I installed the pack and it's in my library, however when I try to use this function  I get the following error:

Error in analyze(m2, CI = 95) : could not find function "analyze"

when I type psycho::analyze also nothing comes up. Any idea about this problem?

**Comment by DominiqueMakowski** [comment]
Dear @kortekss your issue is likely to be normal, as this feature has been improved and transferred to the `report` package. 

You can find more details and workarounds here: https://github.com/neuropsychology/psycho.R/issues/115

**Comment by tessaeagle** [comment]
> Hi,
> 
> I'm having problem about finding the analyse function. I installed the pack and it's in my library, however when I try to use this function I get the following error:
> 
> Error in analyze(m2, CI = 95) : could not find function "analyze"
> 
> when I type psycho::analyze also nothing comes up. Any idea about this problem?

@kortekss were you able to sort this out? I'm having the same issue

**Comment by DominiqueMakowski** [comment]
@tessaeagle you can use the https://github.com/easystats/report package to get these "reporting" functionalities
