### ISSUE TITLE
One Sample t-test error

### ISSUE THREAD

**Issue by sbalci** [neuropsychology/psycho.R#69]
One Sample t-test gives an error. It cannot find a value where there should be TRUE/FALSE. I think it cannot find the `mu = 0` to compare.

```r
result <- t.test(df$Adjusting, 
       mu = 0,
       conf.level = .90) %>% 
      psycho::analyze(result)
```

<img width="556" alt="ekran resmi 2018-06-21 20 28 40" src="https://user-images.githubusercontent.com/7208830/41735384-311499c0-7592-11e8-9c17-1dd63bc653e4.png">

Thanks for the package.

**Comment by DominiqueMakowski** [comment]
@sbalci I cannot reproduce the error. Try updating the version to the latest release:

```r
install.packages("devtools")
library("devtools")
install_github("neuropsychology/psycho.R")
library("psycho")
```
If that doesn't work, let me know!

**Comment by sbalci** [comment]
Thank you very much, it works after the update.
