### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by sbalci** [neuropsychology/psycho.R#70]
Hello,

Do you support other languages? I think as   `psycho::analyze( ... , lang = "TR")`

If so, I may help in translating to Turkish.

Best wishes.

**Comment by DominiqueMakowski** [comment]
@sbalci This is currently not in the plans. 

Although technically *feasible* (although it would require a lot of work as the text is currently generated in a flexible way that would make hard just to translate the text chunks), I'm not currently convinced of its utility: English is the default language for scientific research and it's better to discuss the results in a unified language. Even for students, I believe they should learn to understand the English output as it is the one used in scientific papers... also it's better for standardization of statistical reports. 

But feel free to change my mind about it :)

**Comment by sbalci** [comment]
It is because your very welcoming contributor guideline :) R is still not widely used in Turkey and I want people to find a reason to use R.
I agree that English is mainly used in the literature, and agree with your reasons.
Maybe I can just fork and try if it works.
Best wishes :)

**Comment by DominiqueMakowski** [comment]
Try contributing as much as you want indeed :) 

Nevertheless, I am afraid we alone could do at best translations in turkish and french, and that would be a lot of work, with possible breaks in the code, for not much in the end...

I think that if you have any particular reasons to do something like that in Turkish, you could either do a meta-translation package that would translate the end-output of psycho (maybe using [google translate](https://github.com/ropensci/googleLanguageR)?) or, and I think that's the better option, write a simple and nice tutorial in Turkish that would detail how to use R and, how to understand its output and so on...
