### ISSUE TITLE
"Significantly large"

### ISSUE THREAD

**Issue by CristinaMendonca** [neuropsychology/psycho.R#73]
Hello!,

First of all, nice work on this package! It would've saved me a lot of going back and forth with APA style if I had met it in the past.

I have just started trying it out, but I found that the output of the analyze function for a correlation returns a somewhat odd description:

`The Pearson's product-moment correlation between a and b is significantly large and positive (r(8) = 10, 95% CI [10, 1], p < .001).`

I suppose what is meant is: "significant, large, and positive" (with Oxford comma included, see page 88 of APA's 6th Edition), as the p-value and the significant refers to the test of the obtained correlation value against a null correlation, while the inference that the sentence leads one to make ("significantly large") would only be valid with something more exotic, e.g., something in which we test the null hypothesis that the p-value is equal to or higher than 0.80 (the criterion for large), i.e., a unilateral, lower tail test against the value of 0.80.

```r
library(psycho)

a <- seq(1, 10)
b <- seq(10, 19)

cor_results <- cor.test(a, b)

psycho::analyze(cor_results)
```

**Comment by DominiqueMakowski** [comment]
@CristinaMendonca Sorry for the delayed response, I've been away.

"significant, large, and positive" is indeed what is meant. I agree that the current description is odd, and should be replaced with the one with commas. I shall make the changes for the next version.

Thanks a lot for notifying :)

**Comment by DominiqueMakowski** [comment]
@CristinaMendonca Fixed in the newest version. Do not hesitate if you have any more remarks.
