### ISSUE TITLE
docs link to working

### ISSUE THREAD

**Issue by vsimko** [neuropsychology/psycho.R#8]
![image](https://user-images.githubusercontent.com/7080773/31229379-c7666936-a9e0-11e7-9bbe-15cb554a0e63.png)

the link is broken:
https://github.com/neuropsychology/psycho.R/blob/master/vignettes/overview.R

**Comment by DominiqueMakowski** [comment]
Fixed for now, but waiting for CRAN publication to link toward the built vignettes :)
