### ISSUE TITLE
find_best_model issues

### ISSUE THREAD

**Issue by HugoNjb** [neuropsychology/psycho.R#80]
Dear Dominique,
Thank you very much for your package, I think it will be very useful to me in the future.
I am notably interested in the find_best_model function and I encontered the following bugs while exploring it.

### 1
_find_best_model.stanreg_ gives the following error message when a random intercept is entered in the formula :
```r
df <- psycho::emotion
fit <- stan_lmer(Autobiographical_Link ~ Emotion_Condition + Subjective_Valence + (1|Participant_ID), data=df)
best <- find_best_model(fit)
```
> Error in f_i(data_i = data[i, , drop = FALSE], draws = draws, ...) : 
>   unused argument (k_treshold = k_treshold)

**Solution**
It seems to come from the loo function of the rstanarm package. I added the following lines into _find_best_model.stanreg_ to temporarily solve the problem :
```r
    if (!is.null(k_treshold)) {
      loo <- rstanarm::loo(newfit, k_treshold = k_treshold)
    } else {
      loo <- rstanarm::loo(newfit)
    }
```

<br>

### 2
Inside _find_best_model.stanreg_, warning messages are sent when accessing the loos estimates :
```r
loo$elpd_loo
```
> Warning message:
> Accessing elpd_loo using '$' is deprecated and will be removed in a future release. Please extract the elpd_loo estimate from the 'estimates' component instead.

**Solution**
I replaced them with those lines:
```r
    Estimates <- loo[["estimates"]]
    model <- data.frame(
      formula = formula,
      complexity = complexity - 1,
      R2 = R2s[[formula]],
      looic = Estimates["looic","Estimate"],
      looic_se = Estimates["looic","SE"],
      elpd_loo = Estimates["elpd_loo","Estimate"],
      elpd_loo_se = Estimates["elpd_loo","SE"],
      p_loo = Estimates["p_loo","Estimate"],
      p_loo_se = Estimates["p_loo","SE"],
      elpd_kfold = Estimates["p_loo","Estimate"],
      elpd_kfold_se = Estimates["p_loo","SE"]
    )
```

<br>

### 3
The _find_best_model_ works for [merModLmerTest class](https://www.rdocumentation.org/packages/lmerTest/versions/2.0-36/topics/merModLmerTest-class) used in the lmerTest v2.0-36 package but not for [lmerModLmerTest class](https://www.rdocumentation.org/packages/lmerTest/versions/3.0-1/topics/lmerModLmerTest-class) used in lmerTest v3.0.

```r
df <- psycho::emotion
fit2 <- lmerTest::lmer(Autobiographical_Link ~ Emotion_Condition + Subjective_Valence + (1|Participant_ID), data=df)
best <- find_best_model(fit2)
```

> Error in UseMethod("find_best_model") : 
>   no applicable method for 'find_best_model' applied to an object of class "c('lmerModLmerTest', 'lmerMod', 'merMod')"

**Solution**
From what I understood, the problem seems to come from the _find_combinations.formula_ function. However, I don't know how to simply resolve this problem.

<br>

I am new to github and I will try to push my find_best_model.stanreg enhancement in the dev branch immediately.

Thanks in advance !

**Comment by DominiqueMakowski** [comment]
@HugoNjb Awesome! Let me know if you have any trouble with github 😄 

I'll look into the third issue

Thanks for your help!

**Comment by DominiqueMakowski** [comment]
Github is a total headache at the beginning, but it's worth to persevere. 

I believe there are different of doing this, but here's one possibility:

1. Fork this repo (there is a fork button next to the "star" and "follow" buttons), it will create a copy of this package linked to your account.
2. Download the [github desktop version](https://desktop.github.com/) and log in
3. Clone your fork on your computer (copy it from github to your computer)
4. In desktop github, create a new branch, called for instance "Fix-BestModel" and publish this branch (it will add it to your version of the repo)
5. Do the changes to the files in your local computer
6. Commit the changes to your branch
7. Create a pull request to merge this branch into the "parent" repo into the master branch

Hope that's helpful ^^

**Comment by HugoNjb** [comment]
I think I did it right !
Thank you for the explanation !

**Comment by DominiqueMakowski** [comment]
@HugoNjb I don't have any PR [here](https://github.com/neuropsychology/psycho.R/pulls) right now, I believe you only created the branch in your fork. Try going [here](https://github.com/HugoNjb/psycho.R/pulls) and creating a pull request from `HugoNjb/psycho.R/Fix-BestModel` (i.e., your branch) to `neuropsychology/psycho.R/dev` (comitting to the **dev** branch would be better than to the master which is supposed to be stable)

**Comment by DominiqueMakowski** [comment]
Hey, thanks again for your commit. If you install the dev branch `devtools::install_github("neuropsychology/psycho.R@dev")`, your issues should be gone. 

Let me know!

**Comment by HugoNjb** [comment]
I tested it, and everything seems to work just fine.

Thanks again for the great responses and reactivity !
