### ISSUE TITLE
suggestion: using .zenodo.json

### ISSUE THREAD

**Issue by vsoch** [neuropsychology/psycho.R#86]
Heyo!

I was looking at [your post here](https://neuropsychology.github.io/psycho.R//2018/08/31/cite_packages.html) and wanted to offer a nice, reproducible and programmatic way to confidently link releases with authors (and beyond paper authors, contributors to the code repository!) that sometimes don't get credit that they deserve with a traditional publication model. If you add a .zenodo.json file to the repository to link to a DOI on [zenodo](http://zenodo.org) you can generate programmically in static docs a citation to copy paste (or render it yourself where needed!) The best example I can show you is in nipype:

 -  [example in rendered docs](https://nipype.readthedocs.io/en/latest/about.html)
 -  [post by one of maintainers](http://blog.chrisgorgolewski.org/2017/11/sharing-academic-credit-in-open-source.html) about using it
 -  [the code repo](https://github.com/nipy/nipype)

**Comment by DominiqueMakowski** [comment]
Thanks for that suggestion! But what if my package already has a DOI (10.21105/joss.00470)?

**Comment by vsoch** [comment]
JoSS is actually Zenodo on the backend! Your Joss DOI is associated with --> https://zenodo.org/record/1165620#.W4klw3VKjoo

The general comment wasn't for this package in particular, but for the blog post to educate on ways to do the citations that is linked with it. In your case (since you have Joss) you could actually still make a .zenood.json linked with it. If you were an author with some other DOI that didn't have one for the software, it could still be obtained! The idea is that it is more of a "living DOI" that is specifically for the software that is updated with new software releases (via Github).
