### ISSUE TITLE
find_combinations interaction

### ISSUE THREAD

**Issue by HugoNjb** [neuropsychology/psycho.R#92]
### 1

First of all, the sorting I proposed in issue #90 had a problem when there was more than nine models, as the names MODEL1, MODEL2, MODEL10 are sorted into MODEL1, MODEL10, MODEL2.

Thus, I changed again the _**find_best_model.lmerModLmerTest**_ function, for the formulas to be well integrated into the _best$table_.

```r
  # Model comparison
  comparison <- as.data.frame(do.call("anova", models))

  # Creating row names equivalent to the comparison data frame
  combinations <- as.data.frame(combinations, row.names = paste0("MODEL",seq(1,length(combinations))))
  
  # Reordering the rows in the same way for both combinations and comparison before implementing the formulas
  comparison <- comparison[ order(row.names(comparison)),]
  comparison$formula <- combinations[order(row.names(combinations)),]
  
  # Sorting the data frame by the AIC then BIC
  comparison <- comparison[order(comparison$AIC,comparison$BIC),]
```

<br>

### 2

More importantly, the **_find_combinations_** function doesn't find all the different possible models when _interaction = TRUE_ and when there are three or more fixed factors.

```r
library(psycho)
as.data.frame(find_combinations(Y ~ A + B + C + (1 | X) ,interaction = TRUE, fixed = NULL))
```

> 1.   Y ~ A + (1 | X)
> 2.   Y ~ B + (1 | X)
> 3.   Y ~ C + (1 | X)
> 4.   Y ~ A + B + (1 | X)
> 5.   Y ~ A + C + (1 | X)
> 6.   Y ~ B + C + (1 | X)
> 7.   Y ~ A + B + C + (1 | X)
> 8.   Y ~ A * B + (1 | X)
> 9.   Y ~ A * C + (1 | X)
> 10. Y ~ B * C + (1 | X)
> 11. Y ~ A * B + C + (1 | X)
> 12. Y ~ A * B * C + (1 | X)

In this example it lacks **A+B\*C** and **A\*C+B**.

**Comment by DominiqueMakowski** [comment]
nice!
