### ISSUE TITLE
Rope in summary of stanreg

### ISSUE THREAD

**Issue by To-be-b** [neuropsychology/psycho.R#94]
Hi,

I am not sure but doing analyze with index = "ROPE" does return the ROPE in the print text but not in the summary table. For Baysian correlation it does include both ROPE and overlap. 

I had a quick look at the source and found that the analyze.stanreg does only include the overlap. Is it possible to inlcude the ROPE as well?

Cheers,
Tobi

**Comment by DominiqueMakowski** [comment]
@To-be-b hey yes you're right! In fact, ROPE is a relatively new addition so it's still in the polishing phase but yeah, I'll try to add it to the summary as soon as I have some time (if you manage to add it feel free to make a PR 😉).

**Comment by To-be-b** [comment]
@DominiqueMakowski Thanks for the quick reply.
I may find some time in October. 
It could be vital to add the ROPE to get_contrasts.stanreg as well ( Kruschke, Doing Bayesian data analysis: A tutorial with R, JAGS, and Stan purposes the use of ROPE in Chapt. 19.3.3.)

**Comment by DominiqueMakowski** [comment]
Yes, adding to get_contrasts would definitely be a necessary addition! The implementation should be rather straightforward as the function to compute ROPE already exists, so it's just a matter of inserting it and adding it to the tables. Let's keep ourselves updated, but I'll be probably  able to look into it in October as well :) Thanks for the suggestion!

**Comment by To-be-b** [comment]
I added ROPE to the summary. However, I have no permission to push to dev -> no PR

**Comment by DominiqueMakowski** [comment]
@To-be-b Great! I've created a PR from dev to master, can you add your commits now?

**Comment by To-be-b** [comment]
somehow my PR synched now. Is that alright @DominiqueMakowski ?

**Comment by DominiqueMakowski** [comment]
It's merged #96 thanks :)
